title:  "Through a glass, darkly"
tagline: "Meaningless stuff"
description:
author:
  name: "João Silva"

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Technology', file: 'technology.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'github', link: 'https://github.com/joao-osilva'}
- {icon: 'linkedin', link: 'https://br.linkedin.com/in/vitor191291'}
- {icon: 'envelope', link: 'mailto:vitor191291@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
