title:  "Through a glass, darkly"
tagline:
description:
author:
  name: "João Silva"

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'throughaglass'

menu:
- {name: 'Technology', file: 'technology.html'}
- {name: 'Tags', file: 'tags.html'}
- {name: 'About', file: 'about.html'}
- {name: 'Contact', file: 'contact.html'}

social:
- {icon: 'github', link: 'https://github.com/joao-osilva'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/joao-osilva/'}
- {icon: 'envelope', link: 'mailto:vitor191291@gmail.com'}

tag_page: '/pages/'

google-ID: 'UA-109202128-1'
